---
title: "mississippi_school_district"
format: html
editor: visual
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
options(scipen = 999)
library(tidyverse)
library(dplyr)
library(DT)
library(viridis)
library(janitor)
library(jsonlite)
source("census.R")
source("acfrs_gen_purpose_2020.R")
source("acfrs_gen_purpose_2021.R")
source("acfrs_gen_purpose_2022.R")
df_state <- tibble(state.abb, state.name)
```


```{r}
data_all <- readRDS("data/data_from_dbsite_2020.RDS") %>% 
  rbind(readRDS("data/data_from_dbsite_2021.RDS")) %>% 
  rbind(readRDS("data/data_from_dbsite_2022.RDS"))

MS_sd_acfr <- data_all %>% filter(state == "MS") %>% 
  filter(category == "School District") %>% 
  select(1:2, 12:34)

write.csv(MS_sd_acfr, "output/MS_sd_acfr.csv")
MS_sd_nces <- nces %>% filter(state == "MS")
MS_sd_nces %>% filter()
```

```{r}
MS_sd_acfr %>% left_join(dictionary) %>% 
  select(state, name, year, net_pension_liability, id, ncesID) %>% 
  filter(is.na(ncesID))

```

