---
title: "Query data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DBI)
library(RPostgreSQL)
library(dplyr)
library(stringr)
```

```{r}
# Insert your credentials to connect with the database
con <- dbConnect(dbDriver("PostgreSQL"), 
                 host = "",
                 port=5432, 
                 dbname = "",
                 user = "",
                 password = ""
                 )


statement <- c("SELECT cafrs_state.abbreviation as state,
cafrs_entity.name, CAST(cafrs_entity.census_id as varchar),
cafrs_entity.id, cafrs_entity.nces_district_id,
cafrs_entity.is_city, 
cafrs_entity.is_county, 
cafrs_entity.is_intergovernmental, 
cafrs_entity.is_special_district, 
cafrs_entity.is_state, 
cafrs_entity.is_tribal,
year, category,

total_liabilities, current_liabilities, 
net_pension_liability, net_pension_assets, 
net_opeb_liability, net_opeb_assets, 

leases, loans_outstanding, notes_outstanding,bonds_outstanding,compensated_absences,

charges_for_services, operating_grants, capital_grants, general_revenue, 
cafrs_activities.change_in_net_position, expenses, 
total_operating_revenues, non_operating_revenues, capital_contributions,

greatest(charges_for_services + operating_grants + capital_grants + general_revenue,
   cafrs_activities.change_in_net_position + expenses,
   total_operating_revenues + non_operating_revenues) as revenues,
   
   cafrs_cafr.has_unconfirmed,
   component_unit_of_id
   
FROM cafrs_cafr
INNER JOIN cafrs_entity on (cafrs_cafr.entity_id = cafrs_entity.id)
INNER JOIN cafrs_state on (cafrs_state.id = cafrs_entity.state_id)
INNER JOIN cafrs_netposition on (cafrs_netposition.cafr_id = cafrs_cafr.id)
INNER JOIN cafrs_activities on (cafrs_activities.cafr_id = cafrs_cafr.id)
INNER JOIN cafrs_proprietaryrevenues on (cafrs_proprietaryrevenues.cafr_id = cafrs_cafr.id)
WHERE year = 2022
AND category != 'Non-Profit'
AND is_valid
AND reviewed_date is not null
AND not is_nonstandard"
)
# and is_enterprise_fund is false

data_from_dbsite_2020 <- dbGetQuery(con, statement) %>% 
   as.data.frame() %>% 
   # Fixing wrong census_id (which is government_id) 
#TODO: check with Ron to edit this in database. 
   mutate(census_id = case_when(state == "NY" & name == "Rochester" ~ "33202800800000", 
                                state == "WI" & name == "Madison" ~ "50201301100000",
                              TRUE ~ as.character(census_id)))

saveRDS(data_from_dbsite_2020, "data_from_dbsite_2020.RDS")


# NOTE: change where year = 2021
data_from_dbsite_2021 <- dbGetQuery(con, statement) %>% 
   as.data.frame() %>% 
#Currently in database cencus_id of rochester of NY is: 33305601300000
# IT should be: "33202800800000"
   mutate(census_id = case_when(state == "NY" & name == "Rochester" ~ "33202800800000", 
                                state == "WI" & name == "Madison" ~ "50201301100000", # wrong: 50301301600000 = town of madison
                              TRUE ~ as.character(census_id))) 
saveRDS(data_from_dbsite_2021, "data_from_dbsite_2021.RDS")


data_from_dbsite_2022 <- dbGetQuery(con, statement) %>% 
 as.data.frame() %>% 
   mutate(census_id = case_when(state == "NY" & name == "Rochester" ~ "33202800800000", 
                                state == "WI" & name == "Madison" ~ "50201301100000",
                              TRUE ~ as.character(census_id)))
saveRDS(data_from_dbsite_2022, "data_from_dbsite_2022.RDS")
```


```{r}
data_from_dbsite_2021 %>% filter(str_detect(name, "Mobile County")) 
   select(state, name, general_revenue,
total_operating_revenues,non_operating_revenues)
```


