---
title: "school_districts"
format: html
editor: visual
---

```{r}
library(tidyr)
library(tidyverse)
```


```{r}
nces <- readRDS("data/nces.RDS")
dictionary <- readRDS("data/dictionary.RDS")

acfr_sd <- readRDS("data/acfrs_data.RDS") %>% 
  filter(category == "School District") %>% 
  mutate(id = as.character(id))

acfr_sd %>% group_by(year) %>% summarise(count = n())

nces %>% filter(is.na(enrollment_20) | is.na(enrollment_21) | is.na(enrollment_22)) %>% 
  select(name_nces, state.name, ncesID, enrollment_20, enrollment_21, enrollment_22)

length(nces$ncesID)
nces 
  
  length(setdiff(acfr_sd$id, dictionary$id)) 
  
  dictionary %>% filter(ncesID == "3627660")
  nces %>% filter(ncesID == "3627660")
  nces %>% filter(ncesID == "3622050")
  acfr_sd %>% filter(nces_district_id == "3625980")
  
  anti_join(acfr_sd, dictionary, by = "id") %>% select(state.abb, name, year, id, nces_district_id) %>% filter(!is.na(nces_district_id)) 
  
  acfr_sd %>% filter(!is.na(nces_district_id)) %>% select(state.abb, name,id, nces_district_id) %>% filter(!is.na(nces_district_id)) %>% distinct() %>% rename(ncesID = nces_district_id)  -> foo
  
  foo %>% left_join(nces, by = c("state.abb", "ncesID")) %>% 
    filter(ncesID %in% c("3625980", "3627660")) %>% 
    select(state.abb, name, name_nces, ncesID)
  
  acfr_sd %>% select(state.abb, name, nces_district_id, id) %>% filter(!is.na(nces_district_id)) %>% distinct() -> alreadyInDatabase
dictionary %>% filter(!id %in% dicDoesNothave$id)
```

```{r}
anti_join(alreadyInDatabase, dictionary, by = "id") %>% 
  rename(ncesID = nces_district_id) %>% 
  write.csv("data/_dictionary_7_manually_created.csv")
```





