---
title: "Untitled"
output: html_document
date: "2024-04-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(stringr)
library(rio)
library(tidyr)
```

# Glossary
https://nces.ed.gov/ccd/elsi/glossary.aspx?app=tableGenerator&term=11020,9558,13403,13392,21783,21784,21785,21786,21779,21780,21778,21781,21777,21776,21546,21545,21789,21544,21569,21553,21572,21554,21571,21875&level=PublicSchool&groupby=0

Total Students, All Grades (Excludes AE) [Public School]: 
This count excludes adult education students, which is the number of students enrolled in adult education courses provided by the public elementary/secondary school system.

```{r}

#download data: https://nces.ed.gov/ccd/elsi/tableGenerator.aspx?savedTableID=649124
nces_20 <- import(here::here("data", "ELSI_school year 2019 2020.csv"))
nces_21 <- import(here::here("data", "ELSI_school year 2020 2021.csv"))
nces_22 <- import(here::here("data", "ELSI_school year 2021 2022.csv"))

  # select(`Agency Name`, 
  #        `State Name [District] Latest available year`, 
  #        `State Abbr [District] Latest available year`,
  #        `Agency ID - NCES Assigned [District] Latest available year`,
  #        `Agency Type [District] 2022-23`, 
  #        `Total Students All Grades (Excludes AE) [District] 2022-23`, 
  #        `Full-Time Equivalent (FTE) Teachers [District] 2022-23`)


nces_ELSI <- nces_20 %>% left_join(nces_21) %>% left_join(nces_22) %>% 
  rename(name = 1,
         state.name = 2, 
         state.abb = 3,
         ncesID = 4,
         
         agency_type_20 = `Agency Type [District] 2019-20`,
         agency_type_21 = `Agency Type [District] 2020-21`,
         agency_type_22 = `Agency Type [District] 2021-22`,
         
         enrollment_20 = `Total Students All Grades (Excludes AE) [District] 2019-20`,
         enrollment_21 = `Total Students All Grades (Excludes AE) [District] 2020-21`,
         enrollment_22 = `Total Students All Grades (Excludes AE) [District] 2021-22`,
         
         
         fte_20 = `Full-Time Equivalent (FTE) Teachers [District] 2019-20`,
         fte_21 = `Full-Time Equivalent (FTE) Teachers [District] 2020-21`,
         fte_22 = `Full-Time Equivalent (FTE) Teachers [District] 2021-22`,
         
         
         revenue_nces_20 = `Total Revenue (TOTALREV) [District Finance] 2019-20`,
         revenue_nces_21 = `Total Revenue (TOTALREV) [District Finance] 2020-21`,
         
         expenditure_nces_20 = `Total Expenditures (TOTALEXP) [District Finance] 2019-20`,
         expenditure_nces_21 = `Total Expenditures (TOTALEXP) [District Finance] 2020-21`
    
  ) %>% 
  filter(state.abb != "PR") %>% 
  
  filter(agency_type_20 != "7-Independent Charter District") %>% 
  
  select(-c(9:11, 17:19, agency_type_20, agency_type_21, agency_type_22)) %>% 
  mutate(ncesID = as.character(ncesID),
         ncesID = ifelse(
         nchar(ncesID) == 6, paste0("0", ncesID), ncesID)) %>% 
  
  mutate(across(5:14, as.double))
 
nces_ELSI %>% filter(nchar(ncesID) == 7) 


# Find out top 100 schools are the same across 3 years:
top_schools_by_year <- nces_ELSI %>% 
  select(name, ncesID, enrollment_20, enrollment_21, enrollment_22) %>% 
  pivot_longer(cols = 3:5, 
               names_to = "year",
               values_to = "value") %>% 
  group_by(year) %>% 
  top_n(100, value) %>% 
  ungroup() %>% 
  arrange(year, desc(value))

top100_2020 <- top_schools_by_year %>% 
  filter(year == "enrollment_20")

top100_2021 <- top_schools_by_year %>% 
  filter(year == "enrollment_21")

top100_2022 <- top_schools_by_year %>% 
  filter(year == "enrollment_22")

top100_2020 %>% filter(name %in% setdiff(top100_2020$name, top100_2021$name))

top100_2021 %>% filter(name %in% setdiff(top100_2021$name, top100_2020$name))

# 4 sd 
top100_2021 %>% filter(name %in% setdiff(top100_2021$name, top100_2022$name))


top100_2022 %>% filter(name %in% setdiff(top100_2022$name, top100_2021$name))


nces_enrollment_3yrs <- nces_ELSI %>% filter(ncesID %in% top_schools_by_year$ncesID) %>% select(-c(name, state.name, state.abb))
```


```{r}

# Split the data frame by year
top_schools_lists <- split(top_schools_by_year, top_schools_by_year$year)

# Extract school names from each list element
school_names <- lapply(top_schools_lists, function(df) df$name)

```

