---
title: "Top100 School Districts"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    number_sections: true
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(dplyr)
library(stringr)
library(tidyr)
library(janitor)
library(forcats)
source("nces.R")
source("general_purpose.R")
source("nyc_school_districts.R")
options(scipen = 999)
df <- data_frame(state.abb, state.name)
```

# School districts from Acfrs database

```{r echo = FALSE}
school_districts <- readRDS("data/acfrs_data.RDS") %>% 
  filter(category == "School District") %>% 
  mutate(id = as.character(id)) %>% 
  select(state, any_of(fields_to_select))
```

## Dictionary ACFRs ID ~ NCES ID

```{r echo = FALSE}
dictionary <- readRDS("data/dictionary.RDS") %>% 
  add_row(ncesID = c("4703180"), #ncesID == "4703180" ~ "107203", # Davidson County Board of Education, previously id = 1267426
                  name = c("Metropolitan Nashville Public Schools"),
                  id = c("107203"),
                  state = c("TN")) %>% 
  
#fixing id (old dictionary reflects old acfrs id --> update these new acfrs id currently showing on database)
  mutate(id = case_when(ncesID == "5101260" ~ "1267421", # why previous id = "1250807", # Fairfax County Public Schools
                   ncesID == "5102250" ~ "1250804", #Loudoun County Public Schools	
                   ncesID == "5103130"~	"1250808",# Prince William County Public Schools		VA
                   ncesID == "0803360" ~ "1237862", #City and County of Denver School District No. 1
                   ncesID == "0102370" ~ "1017229",#Mobile County Board of School Commissioners	
                   ncesID == "5103840" ~ "1265776", #School Board of the City of Virginia Beach	
                   ncesID == "5100840" ~ "1267422", #VA	Chesterfield County Public Schools	1267422
                   ncesID == "5101890" ~ "1267423", #VA	Henrico County Public Schools	1267423
                   ncesID == "2502790" ~ "1267424", #MA	Boston Public Schools	
                   ncesID == "3174820" ~ "35480", #NE Omaha City School District 1 = 	Douglas County School District No. 0001	35480
                   ncesID == "2601103" ~ "161679", # MI Detroit Public Schools
                   ncesID == "1602100" ~ "32700", #ID	JOINT SCHOOL DISTRICT NO. 2
         TRUE ~ as.character(id))) 

```


```{r}
# nces %>% select(state.abb, ncesID, enrollment_20, enrollment_21, enrollment_22) -> nces_enrollment
# 
# school_districts %>% select(state, name, id) %>% distinct() %>% 
#   left_join(dictionary) %>% 
#   left_join(nces_enrollment) %>% 
#   filter(!is.na(ncesID)) %>% 
#   mutate(government_level = "school district") #%>% 
#  # write.csv("output/school district_enrollment_20_21_22.csv")
```

# Top 100 SD
```{r}
# filter only top 100
dict_top100_ELSI <- dictionary %>% 
  filter(ncesID %in% top_schools_by_year$ncesID) %>% 
  drop_na(id)

top100_school_districts <- school_districts %>% 
  filter(id %in% dict_top100_ELSI$id) %>% select(-name) %>% 
  left_join(dict_top100_ELSI, by = c("id", "state")) %>% 
  rename(state.abb = state) %>% 
  # get state name
  left_join(df) %>% 

  #join with nces to get county, city info
  left_join(nces, by = c("ncesID", "state.abb", "state.name")) %>% 
  rename(name = name.x) %>% 
  select(-name.y) %>% 
#bind with NYC
  rbind(nyc_top5) %>% 
  
  #TODO: remove this once acfrsvalue table in database is fixed
  
  mutate(net_pension_liability = ifelse(name == "Rutherford County Schools", 0, net_pension_liability),
         net_opeb_assets = ifelse(name == "Rutherford County Schools", 0, net_opeb_assets),
         current_assets = ifelse(name == "Rutherford County Schools" & year == 2020, 229017352, current_assets),
         current_assets = ifelse(name == "Rutherford County Schools" & year == 2021, 284767091, current_assets))

 
#TODO: check back missing: 
#GA Clayton County Board of education.
#https://www.clayton.k12.ga.us/departments/business-services/financial-reports

top100_school_districts %>% #filter(name == "Rutherford County Schools")
  add_count(ncesID) %>% filter(n < 3) %>% 
  select(state.abb, ncesID, year, name, n)


```


# Export result
```{r}
saveRDS(top100_school_districts, "top100_sd.RDS")

top100_school_districts %>% write.csv("output/top100_sd.csv")
school_districts %>% write.csv("output/all_schooldistricts_3years.csv")
#TODO: ask Geoff about this revenues = expense cases



 
  
 
```




